version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm install -g yarn typescript
      - yarn install
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  files:
    - package-lock.json
    - package.json
    - "dist/**/*"
    - ".platform/**/*" # AWS Elastic Beanstalk configuration files
    - ".ebextensions/**/*" # AWS Elastic Beanstalk configuration files
  discard-paths: no
