export const streetTypeAbbreviations: Record<string, string> = {
  st: "st",
  str: "st",
  ave: "ave",
  blvd: "blvd",
  dr: "dr",
  rd: "rd",
  ln: "ln",
  pl: "pl",
  cir: "cir",
  ct: "ct",
  sq: "sq",
  ter: "ter",
  pkwy: "pkwy",
  fwy: "fwy",
  hwy: "hwy",
  aly: "aly",
  way: "way",
  street: "st",
  avenue: "ave",
  boulevard: "blvd",
  drive: "dr",
  road: "rd",
  lane: "ln",
  place: "pl",
  circle: "cir",
  court: "ct",
  square: "sq",
  terrace: "ter",
  parkway: "pkwy",
  freeway: "fwy",
  highway: "hwy",
  alley: "aly",
};

export const directionAbbreviations: Record<string, string> = {
  n: "n",
  s: "s",
  e: "e",
  w: "w",
  ne: "ne",
  nw: "nw",
  se: "se",
  sw: "sw",
  north: "n",
  south: "s",
  east: "e",
  west: "w",
  northeast: "ne",
  northwest: "nw",
  southeast: "se",
  southwest: "sw",
};

export const otherComponents: Record<string, string> = {
  u: "unit",
  ste: "suite",
  fl: "floor",
  unit: "unit",
  suite: "suite",
  floor: "floor",
};
